[project]
name = "cc-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "numpy>=2.3.2",
    "polars>=1.32.3",
    "requests>=2.32.5",
    "warcio>=1.7.5",
]
